services:
  app:
    image: sohaibkhiaf/usermanagementapi-app:cache
    container_name: user_management_api
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /var/www
    volumes:
      - appdata:/var/www
    networks:
      - user_management_network

  webserver:
    image: sohaibkhiaf/usermanagementapi-webserver:cache
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - appdata:/var/www
    depends_on:
      - app
    networks:
      - user_management_network

  db:
    image: mariadb:10.4.32
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - user_management_network

networks:
  user_management_network:

volumes:
  dbdata:
  appdata:

